version: '3.1'

services:
  db:
    image: postgres:10.5-alpine
    env_file:
      - .env
    ports:
      - "54321:5432"
    volumes:
      - ./scripts/build.sql:/docker-entrypoint-initdb.d/build.sql
      - ./scripts/fill.sql:/docker-entrypoint-initdb.d/fill.sql