version: '3.1'

services:
  db:
    image: postgres:10.5-alpine
    env_file:
      - .env
    ports:
      - "54321:5432"
    volumes:
      - ./scripts/10_build.sql:/docker-entrypoint-initdb.d/10_build.sql
      - ./scripts/20_fill.sql:/docker-entrypoint-initdb.d/20_fill.sql
      - ./scripts/30_indexes.sql:/docker-entrypoint-initdb.d/30_indexes.sql